<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.groovier</groupId>
        <artifactId>groovier-plugin</artifactId>
        <version>0.0.55-SNAPSHOT</version>
    </parent>

    <artifactId>groovier-eld-plugin</artifactId>

    <properties>
        <eld.version>2.0.51-SNAPSHOT</eld.version>
    </properties>

    <repositories>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/ELDependenci/eldependenci</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.groovier</groupId>
            <artifactId>groovier-common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eldependenci</groupId>
            <artifactId>eldependenci-bukkit</artifactId>
            <version>${eld.version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eldependenci</groupId>
            <artifactId>eldependenci-bungee</artifactId>
            <version>${eld.version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.inject</groupId>
                    <artifactId>javax.inject</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.eldependenci</groupId>
            <artifactId>eldependenci-addon</artifactId>
            <version>${eld.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eldependenci</groupId>
            <artifactId>eldependenci-addon</artifactId>
            <version>${eld.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <outputFile>${user.dir}/outputs/${build.finalName}.jar</outputFile>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
