name: build artifacts for 1.21
on:
  push:
    branches:
      - feat/1.21
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        id: checkout-source
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'
      - name: 'Package Jar'
        run: mvn -B package --file ./pom.xml
      - name: 'upload artifacts'
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: groovier-plugin
          path: './groovier-plugin/target'
